spring.application.name=furniCaregateway
server.port = 8082
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/FurniKart
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9090/realms/FurniKart/protocol/openid-connect/certs
spring.main.allow-bean-definition-overriding=true
debug=true

# Gateway CORS Configuration
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOriginPatterns="http://localhost:3000"
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

# Gateway Routes
spring.cloud.gateway.server.webflux.routes[0].id=home-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/home

eureka.client.enabled=false
spring.cloud.discovery.enabled=false
